### ISSUE TITLE
IoT policy error [AWS_ERROR_MQTT_CANCELLED_FOR_CLEAN_SESSION]

### ISSUE THREAD

**Issue by acerbisgianluca** [doronbl/aws-iot-fleet-provisioning-trusted-user-workshop#1]
Hi, I followed your tutorial and I really appreciated it. I managed to exchange the claim certificate with the unique one, but I encountered a problem while testing the device's shadow using [shadow.py](https://github.com/aws/aws-iot-device-sdk-python-v2/blob/main/samples/shadow.py).

After it subscribes to some shadow's topics, it raises the following excetion and then it disconnects from the broker: **awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_CANCELLED_FOR_CLEAN_SESSION: Old requests from the previous session are cancelled, and offline request will not be accept.**

So I tried changing the resource of the first statement from `arn:aws:iot:eu-west-1:XXXXXXXXX:topic/${iot:Connection.Thing.ThingName}/*` to `arn:aws:iot:eu-west-1:XXXXXXXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/*` and it worked.

Is it a problem related to the policy o to the script?

**Comment by doronbl** [comment]
Happy to know you are using it.
From a quick look on the error, I suspect that your connection to MQTT broker is utilizing the old, temporary, certificate. After you acquire the permanent certificate you should terminate the connection and re-open a new one, so the new certificate will be used.
Let me know if my assumption is incorrect and I'll dive deeper into it.

**Comment by acerbisgianluca** [comment]
I don't think that it could be the problem because I'm using the certificate obtained using IoT device client and the error is raised when the script tries to get the current shadow, so it's already connected e subscribed to some topics, as you can see here:

```
Connecting to XXXXXXXXXXX-ats.iot.eu-west-1.amazonaws.com with client ID 'device-client-fp'...
Connected!
Subscribing to Update responses...
Subscribing to Get responses...
Subscribing to Delta events...
Requesting current shadow state...
Exiting sample due to exception.
Traceback (most recent call last):
  File "shadow.py", line 391, in <module>
    publish_get_future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_CANCELLED_FOR_CLEAN_SESSION: Old requests from the previous session are cancelled, and offline request will not be accept.
Disconnecting...
Disconnected.
```

Adding the topic prefix fixed the problem:
> So I tried changing the resource of the first statement from arn:aws:iot:eu-west-1:xxxxxxxx:topic/${iot:Connection.Thing.ThingName}/* to arn:aws:iot:eu-west-1:XXXXXXXXX:topic/$aws/things/${iot:Connection.Thing.ThingName}/* and it worked.

**Comment by doronbl** [comment]
I need to check further. I do remember facing this error once as well. As far as I remember it was something silly I did on my end. Do you have any hints on the IoT service logs in CloudWatch. You can enable logs from the settings part in the IoT console.
Anyway, you should not use $aws as this is reserved topic and probably is not doing what you try to achieve.

And last thing, please edit the messages and mask your account id, it is better to avoid publishing it to reduce attack surface.

**Comment by acerbisgianluca** [comment]
> And last thing, please edit the messages and mask your account id, it is better to avoid publishing it to reduce attack surface.

Oops, thank you, didn't notice that.

This is my first time working on IoT Core and until now I didn't know that the topics which start with "$aws" are reserved. So, could it be a problem related to shadow's permissions in the policy?

I tried adding a new statement with 3 shadow's actions (get, delete, update), but I couldn't get it work.

**Comment by acerbisgianluca** [comment]
Found out that the [line](https://github.com/aws/aws-iot-device-sdk-python-v2/blob/7ceb5e5c55e7e6b561d8be4b0ce7030d9d012eaa/samples/shadow.py#L384) which causes that error tries to publish a message to the following topic: `$aws/things/{0.thing_name}/shadow/get`.
That's why adding "$aws/things/......" prefix fixes the issue.

**Comment by doronbl** [comment]
I was offline for few days. Happy to hear your issue is resolved.
Do you need any further help?

**Comment by acerbisgianluca** [comment]
Nope, thank you
